language: node_js

node_js:
  - "node"
  - "10"
  - "8"
  - "7"

cache: npm

install:
  - npm install
  - npm i -g npx

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npx jest --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

